services:
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - BROWSER_MIN_HEIGHT=100
      - BROWSER_MIN_WIDTH=300
  grafana:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    depends_on:
      - renderer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
